cartesian_motion_controller:
  type: "position_controllers/CartesianMotionController"
  end_effector_link: "ft_sensor_frame"
  robot_base_link: "world"
  target_frame_topic: "command"
  joints:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

  pd_gains:
      trans_x: {p: 10.0}
      trans_y: {p: 10.0}
      trans_z: {p: 10.0}
      rot_x: {p: 1.0}
      rot_y: {p: 1.0}
      rot_z: {p: 1.0}