cartesian_motion_position_controller:
  type: "position_controllers/CartesianMotionController"
  end_effector_link: &ee "tool0"
  robot_base_link: &ref "base"
  target_frame_topic: "command"
  joints: &robot_joints
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

  pd_gains: &pd
    p: &p 8.0
    d: &d 0.4  
    trans_x: {p: *p, d: *d}
    trans_y: {p: *p, d: *d}
    trans_z: {p: *p, d: *d}
    rot_x: {p: *p, d: *d}
    rot_y: {p: *p, d: *d}
    rot_z: {p: *p, d: *d}
  
  solver: &solver
    error_scale: 4.0
    iterations: 10

# cartesian_motion_velocity_controller:
#   type: "velocity_controllers/CartesianMotionController"
#   end_effector_link: *ee
#   robot_base_link: *ref
#   target_frame_topic: "command"
#   joints: *robot_joints

#   pd_gains: *pd

# cartesian_eik_position_controller:
#   type: "position_controllers/CartesianEikController"
#   end_effector_link: *ee
#   robot_base_link: *ref
#   target_traj_topic: "command"
#   joints: *robot_joints

#   pd_gains: *pd

# cartesian_eik_velocity_controller:
#   type: "velocity_controllers/CartesianEikController"
#   end_effector_link: *ee
#   robot_base_link: *ref
#   target_traj_topic: "command"
#   joints: *robot_joints

#   pd_gains: *pd
