cartesian_motion_position_controller:
  type: "position_controllers/CartesianMotionController"
  ik_solver: "forward_dynamics"
  end_effector_link: &ee "tool0"
  robot_base_link: &ref "base"
  target_frame_topic: "command"
  joints: &robot_joints
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

  pd_gains:
    p: &p 10.0
    d: &d 0.0  
    trans_x: {p: *p, d: *d}
    trans_y: {p: *p, d: *d}
    trans_z: {p: *p, d: *d}
    rot_x: {p: *p, d: *d}
    rot_y: {p: *p, d: *d}
    rot_z: {p: *p, d: *d}
  
  solver:
    error_scale: 1.1
    iterations: 1
    
    forward_dynamics:
      link_mass: 0.1
  
  cart_error:
    vel_err_scale: 1.0

cartesian_eik_position_controller:
  type: "position_controllers/CartesianMotionController"
  ik_solver: "eik"
  end_effector_link: *ee
  robot_base_link: *ref
  target_frame_topic: "command"
  joints: *robot_joints

  pd_gains:
    p: &ep 1.0
    d: &ed 0.0 
    trans_x: {p: *ep, d: *ed}
    trans_y: {p: *ep, d: *ed}
    trans_z: {p: *ep, d: *ed}
    rot_x: {p: *ep, d: *ed}
    rot_y: {p: *ep, d: *ed}
    rot_z: {p: *ep, d: *ed}
  
  solver:
    error_scale: 10
    iterations: 1
    
    eik:
      eik_damp: 100
    
  cart_error:
    vel_err_scale: 0.4
  
cartesian_eik_velocity_controller:
  type: "velocity_controllers/CartesianMotionController"
  ik_solver: "eik"
  end_effector_link: *ee
  robot_base_link: *ref
  target_frame_topic: "command"
  joints: *robot_joints

  pd_gains:
    p: *ep
    d: *ed
    trans_x: {p: *ep, d: *ed}
    trans_y: {p: *ep, d: *ed}
    trans_z: {p: *ep, d: *ed}
    rot_x: {p: *ep, d: *ed}
    rot_y: {p: *ep, d: *ed}
    rot_z: {p: *ep, d: *ed}
  
  solver:
    error_scale: 1.0
    iterations: 1
    
    eik:
      eik_damp: 100
    
  cart_error:
    vel_err_scale: 1.0
